# Database Configuration
spring.datasource.url=jdbc:mysql://staging-db-server:3306/addressbook_db?useSSL=true&serverTimezone=UTC
spring.datasource.username=staging_user
spring.datasource.password=staging_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=25000

# Logging Settings
logging.level.root=WARN
logging.file.name=logs/staging-addressbook-app.log
