# Application Name
spring.application.name=AddressBookApp

# Set active profile (Change this in different environments)
spring.profiles.active=dev

# Common Logging Defaults
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level [%thread] %logger{36} - %msg%n
logging.file.name=logs/addressbook-app.log
